server:
  applicationConnectors:
  - type: http
    port: 7070
    bindHost: 0.0.0.0
  adminConnectors:
  - type: http
    port: 7071
    bindHost: 0.0.0.0
logging:
  appenders:
    # - type: console  # debug only
    - type: file
      currentLogFilename: ./logs/dropwizard.log
      archivedLogFilenamePattern: ./logs/dropwizard-%d.log.gz
      archivedFileCount: 5
      timeZone: UTC